#!/bin/bash
echo "Informações do Sistema:"
echo "======================="
echo "Usuario Logado:: $(hostname)"
echo "Kernel: $(uname -r)"
if [ -f /etc/os-release ]; then
    source /etc/os-release
    echo "Distribuição: $NAME"
    echo "Versão: $VERSION"
fi
echo "Arquitetura do Sistema: $(arch)"
echo "Informações da CPU:"
echo "Modelo da CPU: $(cat /proc/cpuinfo | grep 'model name' | uniq | awk -F ':' '{print $2}')"
echo "Número de núcleos: $(cat /proc/cpuinfo | grep 'processor' | wc -l)"
echo "Total de Memória RAM: $(free -m | grep Mem | awk '{print $2}') MB"
echo "Uso de Disco:"
df -h | grep -E '/dev/sd|/dev/nv'
echo "Endereço IP: $(hostname -I)"
echo "Data e Hora Atuais: $(date)"
echo "Partições de Disco:"
 df -h
echo "Usuários do Sistema:"
cut -d ':' -f 1 /etc/passwd
echo "Pacotes Instalados:" dpkg -l | grep '^ii' | awk '{print $2}'
echo "Por favor, selecione o sistema que você está usando:"
echo "1. Debian/Ubuntu"
echo "2. Red Hat/CentOS"
read -p "Digite o número correspondente ao seu sistema: " opcao
if [ "$opcao" == "1" ]; then
    echo "Pacotes Instalados (Debian/Ubuntu):"
    dpkg -l | grep '^ii' | awk '{print $2}'
elif [ "$opcao" == "2" ]; then
    echo "Pacotes Instalados (Red Hat/CentOS):"
    rpm -qa
else
    echo "Opção inválida. Por favor, selecione 1 ou 2."
fi
